AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to process CloudWatch logs

Resources:
  LogProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: log-processor
      Runtime: python3.9
      Handler: log_processor.lambda_handler
      Role: !ImportValue LambdaExecutionRoleArn
      Timeout: 60
      MemorySize: 256
      Code:
        S3Bucket: !ImportValue LambdaCodeBucket
        S3Key: log_processor.zip
      Environment:
        Variables:
          LOGS_BUCKET: !ImportValue LogsBucketName
          SNS_TOPIC_ARN: !ImportValue ObservabilityAlertsTopicArn
          OPENSEARCH_ENDPOINT: !ImportValue OpenSearchEndpoint
          OPENSEARCH_INDEX: observability-logs
          
  LogProcessorLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogProcessorLambda
      Action: lambda:InvokeFunction
      Principal: logs.amazonaws.com
      SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:EC2-syslog:*

  EC2SyslogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: EC2-syslog
      RetentionInDays: 7   # économie

  CloudWatchLogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn:
      - LogProcessorLambdaPermission
      - EC2SyslogGroup
    Properties:
      DestinationArn: !GetAtt LogProcessorLambda.Arn
      FilterPattern: ""
      LogGroupName: EC2-syslog

